### ISSUE TITLE
Doubt on how tu use ASO

### ISSUE THREAD

**Issue by JACKYNIKK** [Kaleidophon/deep-significance#18]
@Kaleidophon Good evening, sorry i'm not sure i understood how the ASO function works. 
For example if i run:
"
my_model_scores = scores_AUROC_Resnet
baseline_scores = scores_AUROC_Mobilenet

min_eps = aso(my_model_scores, baseline_scores, seed=seed, show_progress=False, confidence_score 0.95)"
from what i understood min_eps should be the upper bound to the amount of violation of the stochastic order.
What i don't understand is how the samples F* and G* are extracted. I mean in the original paper it says inverse transform sampling is used. While as far as i understood in your paper on this repository it is stated in (3) that these samples are obtained bootstrapping. Does this mean the same thing? Are they inverselly sampled casually or is a bootstrapping involving a constant similar to the one used in power analysis used? maybe i'm just confusing terms and they mean the same thing.
Thank you in advance and have a good evening

**Comment by Kaleidophon** [comment]
Hey @JACKYNIKK! Bootstrapping is not a sampling technique per se, but an estimation method performing re-sampling. The re-sampling in the bootstrapping is performed by using the inverse transform sampling, meaning that we sample from a uniform distribution and run them through the empirical inverse CDF of our original scores, thereby obtaining new samples that follow the distribution of our original results. You can see this happening in the code [here](https://github.com/Kaleidophon/deep-significance/blob/00d60744e00c56248b323afcfb09fbaf052f6c01/deepsig/aso.py#L506) and [here](https://github.com/Kaleidophon/deep-significance/blob/00d60744e00c56248b323afcfb09fbaf052f6c01/deepsig/aso.py#L419): In the first code line, we sample from uniform and pass it through the inverse CDF. Since we use the empirical inverse CDF, samples are drawn using the logic in the second snippet.

Let me know if that helped or if you have any more questions!

**Comment by JACKYNIKK** [comment]
That helped a lot, i'm closing the issue since i think it is clear now. Thank you!
