### ISSUE TITLE
Holm-Bonferroni vs Bonferroni

### ISSUE THREAD

**Issue by ndalton12** [Kaleidophon/deep-significance#2]
Hello, I am not as familiar with statistical testing as I ought to be, but I found this package interesting. Is the Bonferonni statistic used here actually the [Holm-Bonferroni statistic](https://en.wikipedia.org/wiki/Holm%E2%80%93Bonferroni_method)? The code matches the definition used by wikipedia, as linked before.

https://github.com/Kaleidophon/deep-significance/blob/21f9251f6279af77c3d788308412e78556a0c170/deepsig/correction.py#L81

Great package by the way!

**Comment by Kaleidophon** [comment]
I believe you're right! The equation this is based on comes from [Dror et al. (2017)](https://watermark.silverchair.com/tacl_a_00074.pdf?token=AQECAHi208BE49Ooan9kkhW_Ercy7Dm3ZL_9Cf3qfKAc485ysgAAAn0wggJ5BgkqhkiG9w0BBwagggJqMIICZgIBADCCAl8GCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMr0FVOnnn3OdY2TmIAgEQgIICMGQ4mNigivCNKN9C7o6Vri-0GB8XCasw-yH1eOYF4TCWdS6xLJFU-Jjy85aRdm90fiMuawu3Mq3HE-sP-8KBjciZy9lX7SrjJZVAL-bG275h9xP2XFb1_v13keMeK9bb2saiOUuEs_qcw7ZIPRi2xW79axNMmIoGYuQRpQI33n3OiqY7k0mGuGTMnl9iFQFtix_I9fBSSuh69Eh6J763s6fzc2e3NINP3pBeppjvpms5qGC8dDyO-C8ifN0Gme7_pTCXNvtL8HuA1ivy1kZlT6wyyBn8Mmq6B5-uFHsqVqTWYCqSTwfImis9aEbiz8zUOivBvkPVIx2Hou2lCS45A9q4JVWEXOoBZYpCeKVXL1B7plSFosNMgMin4bE7bkjnV6Y7jwmgShG2JiScySy54N0A7GFsALDXTy-99UYDuUIXD0-JgZUupXOtZDxzu98d1PW9cvXgnLSiXxC1ko_BExLYDx2T4M4_mOJNDeAUjpUNNyF_MmyzdIvKhF02vF9zoW1YJJPRK9dCuOg6sM5kCc6ES0mLrHLRmPr-QVVtyaoi4LyTO6U_Z1J6sWZXHP6c8VQqVJ47uL4wzAj4AuJP6srGjSqEiBGXZj8GuYXmGpCqLH5NXbscifkarrNw9krrb4JzW8FCFg7fO92NRfpsYRUixgkxijEwbcC6DHLOuoOV0SaXjIUJySABr-6A-kC9EqHtl7qBlKZZM7_GsDQT50AgkqGjTZAabBTyN6SicgVG) Eq. 2 and was taken pretty verbatim from the corresponding line in the code base [here](https://github.com/rtmdrr/replicability-analysis-NLP/blob/63c0d414e64fcacc5ee60ca2c04bb3173118db25/Replicability_Analysis.py#L51), which I credited in the readme.

I am giving this answer with some caution because for me, this project was also about understanding statistical significance testing better, but I do not claim to be as knowledgeable about the topic as a statistician :-)

**Comment by Kaleidophon** [comment]
Closing this unless there are further questions or comments.
